package org.ozinger.ika

import io.mockk.mockkClass
import org.junit.jupiter.api.extension.RegisterExtension
import org.koin.core.component.inject
import org.koin.test.KoinTest
import org.koin.test.junit5.KoinTestExtension
import org.koin.test.junit5.mock.MockProviderExtension
import org.ozinger.ika.configuration.Configuration
import org.ozinger.ika.koin.*

abstract class AbstractTest : KoinTest {
    protected val configuration: Configuration by inject()

    @JvmField
    @RegisterExtension
    val koinTestExtension = KoinTestExtension.create {
        modules(configurationModule)
        modules(eventModule, definitionModule, storeModule)
        modules(autoGeneratedHandlerModule)
    }

    @JvmField
    @RegisterExtension
    val mockProvider = MockProviderExtension.create { clazz ->
        mockkClass(clazz)
    }
}